version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - bookmark-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bookmark-network

networks:
  bookmark-network:
    driver: bridge
